Repository algorithm-study-2408/coding-tests-study-2412, pull requests merged in 2025-01, with the labels that each got.

#63 [홍세영] 5주차 월요일 일일문제풀이
  src/seyoung/_2412_5주차/요격시스템.java
Labels: 코드리뷰, 시뮬레이션

#64 [이재훈] 5주차 월요일, 화요일 일일문제풀이
  src/jaehoon/_05주차/Lv02_요격시스템.java
  src/jaehoon/_05주차/Lv02_이모티콘_할인행사.java
  src/jaehoon/_05주차/Lv02_이모티콘_할인행사_리팩토링.java
Labels: 코드리뷰, DFS, 시뮬레이션

#62 [우효진] 5주차 월요일 일일 문제풀이
  src/hyojin/simulation/요격시스템.java
Labels: 코드리뷰, 시뮬레이션

#67 [이재훈] 5주차 수요일 일일 문제풀이
  src/jaehoon/_00연습/순열_조합/순열.java
  src/jaehoon/_00연습/순열_조합/조합_재귀.java
  src/jaehoon/_00연습/순열_조합/조합_중첩for문.java
  src/jaehoon/_00연습/스택/BOJ_17298_오큰수.java
  src/jaehoon/_00연습/스택/Lv02_올바른괄호.java
  src/jaehoon/_00연습/스택/Lv02_주식가격.java
  src/jaehoon/_05주차/Lv02_무인도_여행_BFS.java
  src/jaehoon/_05주차/Lv02_무인도_여행_DFS.java
  src/jaehoon/_05주차/Lv02_요격시스템.java
Labels: 코드리뷰, BFS, DFS

#68 [홍세영] 5주차 수목 일일문제풀이
  src/seyoung/_2412_5주차/무인도여행.java
  src/seyoung/_2412_5주차/조이스틱.java
Labels: 코드리뷰, 그리디, BFS

#70 [홍세영] 5주차 금요일 일일 문제풀이
  src/seyoung/_2412_5주차/마법의엘레베이터.java
Labels: 코드리뷰, DP

#66 [우효진] 5주차 목요일 일일 문제풀이
  src/hyojin/simulation/조이스틱.java
Labels: 코드리뷰, 시뮬레이션

#71 [우효진] 6주차 월요일 일일 문제풀이
  src/hyojin/greedy/지뢰찾기.java
Labels: 코드리뷰, 그리디

#69 [정연재] 5주차 목요일 금요일 일일 문제풀이
  src/yeonjae/greedy/마법의엘레베이터.java
  src/yeonjae/greedy/조이스틱.java
Labels: 코드리뷰, 그리디, DP

#72 [이재훈] 6주차 월요일 일일 문제풀이
  src/jaehoon/_06주차/BOJ_9082_지뢰찾기.java
  src/jaehoon/_06주차/BOJ_9082_지뢰찾기2.java
Labels: 코드리뷰, 그리디

#75 [이재훈] 6주차 화요일 일일문제풀이
  src/jaehoon/_06주차/BOJ_1461_도서관.java
  src/jaehoon/_06주차/BOJ_1461_도서관_우선순위큐.java
Labels: 코드리뷰, 그리디

#76 [홍세영] 6주차 화요일 일일문제풀이
  src/seyoung/_2501_6주차/도서관.java
Labels: 코드리뷰, 그리디

#78 [이재훈] 6주차 수, 목요일 일일문제풀이
  src/jaehoon/_06주차/BOJ_13458_시험감독.java
  src/jaehoon/_06주차/BOJ_3109_빵집.java
Labels: 코드리뷰, 그리디, DFS

#77 [우효진] 6주차 수요일 일일문제풀이
  src/hyojin/greedy/BOJ_1541_잃어버린괄호.java
  src/hyojin/greedy/BOJ_1931_회의실배정.java
  src/hyojin/greedy/도서관.java
  src/hyojin/greedy/빵집.java
Labels: 코드리뷰, 그리디

#81 [우효진] 7주차 월요일 일일문제풀이
  src/hyojin/simulation/BOJ_20546_기적의매매법.java
Labels: 코드리뷰, 시뮬레이션
