Repository algorithm-study-2408/coding-tests-study-2412, pull requests merged in 2025-02, with the labels that each got.

#80 [이재훈] 7주차 월요일 일일문제풀이 - 기적의 매매법
  src/jaehoon/_07주차/BOJ_20546_기적의_매매법.java
Labels: 코드리뷰, 시뮬레이션

#82 [우효진] 8주차 월요일 일일문제풀이
  src/hyojin/simulation/BOJ_10809_기상캐스터.java
Labels: 시뮬레이션

#84 [이재훈 ]8주차 월, 화요일 일일문제풀이
  src/jaehoon/_08주차/BOJ_10709_기상캐스터.java
  src/jaehoon/_08주차/BOJ_20546_기적의_매매법.java
Labels: 시뮬레이션

#85 [이재훈] 8주차 실전문제풀이
  src/jaehoon/_08주차/BOJ_11559_PuyoPuyo.java
Labels: BFS, 시뮬레이션

#86 [이재훈] 9주차 1, 2번 문제풀이
  src/jaehoon/_09주차/BOJ_20125_쿠키의_신체_측정.java
  src/jaehoon/_09주차/BOJ_3085_사탕게임.java
Labels: 코드리뷰, 시뮬레이션
